### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by i-am-the-slime** [jvliwanag/purescript-literals#13]
I'd like to add this back to the package set (and also untagged-union). A new release of this would be a good start.

**Comment by jvliwanag** [comment]
Hi @i-am-the-slime , I’m afraid I haven’t done purescript in a good while now. Open on helping me gather what needs to be done on this front to add this back? Looking for maintainer

**Comment by i-am-the-slime** [comment]
Hey @jvliwanag . Sad to hear you're unable to use PureScript.
I just invited you to @rowtype-yoga . The easiest could be for you to transfer ownership of the whole repo to that organization.
There are a few people there who will be able to maintain the libraries there!

**Comment by jvliwanag** [comment]
Went ahead and transferred this. Appreciate the invite.
