### ISSUE TITLE
Consider renaming this package

### ISSUE THREAD

**Issue by paluh** [jvliwanag/purescript-literals#2]
My propositions:

* `literals` as we have multiple of them now

* `typelevel-literals`

* `reflected` or `reflected-literals`

I think that `literal` is a bit to generic. Of course naming is a mainly matter of personal opinion so I understand if you just close this issue :-P

**Comment by jvliwanag** [comment]
Let's use `literals`, mind adding that in #1 ?

**Comment by paluh** [comment]
Cool. I will add this change to #1

**Comment by paluh** [comment]
Thanks for pushing this forward! I like this lib more and more ;-)
